name: Deploy to production

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      ECR_REPOSITORY: simplebank
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Debug GitHub OIDC claims
        run: |
          TOKEN_JSON=$(curl -s \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")

          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r .value)

          echo "$ID_TOKEN" | cut -d '.' -f2 | base64 -d 2>/dev/null | jq .


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::449386169831:role/gh-actions-role
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            -t $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            .

      - name: Push Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG